spring:
    config:
        activate:
            on-profile: dev
    devtools:
        add-properties: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate:
                format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend
    server: http://localhost:${server.port}
    # server: http://localhost:8080
    title: Backend service
    version: 1.0.0

jwt:
    secretkey: dev
    