spring:
    config:
        activate:
            on-profile: dev
    devtools:
        add-properties: true
    datasource:
        url: jdbc:mysql://localhost:3306/hotelmanagement
        username: root
        password: Tuan1806@
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
        show-sql: false
        hibernate:
            ddl-auto: none
        

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend
    server: http://localhost:${server.port}
    # server: http://localhost:8080
    title: Backend service
    version: 1.0.0

jwt:
    secretkey: dev
    