services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: hotelmanagement
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - default
  # postgres:
  #   image: postgres
  #   container_name: postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     PGDATA: /data/postgres
  #   volumes:
  #     - postgres:/data/postgres
  #     - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - default


  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    
    networks:
      - default

networks:
  default:
    name: backend

volumes:
  mysql-data:

